version: "3.9"

services:
  web-service:
    build: .
    image: my-image
    container_name: my-container
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__PG_CONNECTION_STRING=Host=db;Port=5432;Database=mydb;Username=postgres;Password=postgres
    depends_on:
      - migrate 
    restart: always

  db:
    image: postgres
    container_name: psql-container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb

  migrate:
    image: my-image
    depends_on: 
      - db
    entrypoint: ["dotnet", "ef", "database", "update"]
    environment: 
      - ConnectionStrings__PG_CONNECTION_STRING=Host=db;Port=5432;Database=mydb;Username=postgres;Password=postgres
