services:
  migrate:
    image: my-app:migrate
    container_name: migrate-container
    environment:
      - DB_STR=Host=postgres-container;Port=5432;Database=mydb;Username=postgres;Password=postgres
    command: ["--connection", "${DB_STR}"]
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb