services:
  migrate:
    image: my-app:migrate
    container_name: migrate-container
    environment:
      - ConnectionStrings__PG_CONNECTION_STRING=Host=db;Port=5432;Database=mydb;Username=postgres;Password=postgres
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb